/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        "background-secondary": "var(--background-secondary)",
        "background-tertiary": "var(--background-tertiary)",
        "background-elevated": "var(--background-elevated)",
        primary: "var(--primary)",
        "primary-dark": "var(--primary-dark)",
        "primary-light": "var(--primary-light)",
        foreground: "var(--foreground)",
        "foreground-muted": "var(--foreground-muted)",
        "foreground-subtle": "var(--foreground-subtle)",
        teal: "var(--teal)",
        "teal-light": "var(--teal-light)",
        indigo: "var(--indigo)",
        card: "var(--card-bg)",
        "card-border": "var(--card-border)",
        "card-border-hover": "var(--card-border-hover)",
        border: "var(--border-color)",
        input: "var(--input-bg)",
        "input-border": "var(--input-border)",
        "input-border-focus": "var(--input-border-focus)",
        sidebar: "var(--sidebar-bg)",
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        muted: "var(--muted)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Segoe UI", "Helvetica Neue", "Arial", "sans-serif"],
        mono: ["var(--font-geist-mono)", "monospace"],
      },
      animation: {},
      keyframes: {},
    },
  },
  plugins: [],
};